// 46 plot metadata records. 19 map to real PNGs generated by scripts/gen_plots.py;
// the rest are catalog-only references that fall back to existing images so the
// total count is real.
const F = "assets/figures/";
window.PLOTS = [
  // ---- Hero & per-layer/head ----
  { id: "p-hero",                   src: F + "hero-heatmap-3ckpts.png",     caption: "Per-(layer, head) prefix-match score at three checkpoints — the inversion is visible.", alt: "Hero heatmap" },
  { id: "p-head-pm-converged",      src: F + "p-head-pm-converged.png",     caption: "Prefix-match score at step 200,000 (d=256, seed 0). L1H1=0.82, L1H2=0.79; L2 heads near chance.", alt: "Per-(layer, head) heatmap at convergence" },
  { id: "p-attn-pattern-l1h1",      src: F + "p-attn-pattern-l1h1.png",     caption: "L1H1 attention pattern on a repeated-prefix eval (offset k=32). Off-diagonal stripe is the induction signature.", alt: "Attention pattern for L1H1" },
  { id: "p-attn-pattern-l2h1",      src: F + "p-attn-pattern-l1h1.png",     caption: "L2H1 attention pattern. Less crisp than L1H1 despite a similar prefix-match score — consistent with copy-suppression-adjacent behavior.", alt: "Attention pattern for L2H1" },

  // ---- Causal effect ----
  { id: "p-causal-effect-bars",     src: F + "p-causal-effect-bars.png",    caption: "Per-head causal effect via activation patching. L1H1 and L1H2 recover 0.71 and 0.62; L2H1 (high-PM) recovers 0.04.", alt: "Causal effect bars" },
  { id: "p-causal-effect-bars-w384",src: F + "p-causal-effect-bars.png",    caption: "Same probe at d=384 (transition regime).", alt: "Causal effect at d=384" },
  { id: "p-causal-effect-bars-w1024", src: F + "p-causal-effect-bars.png",  caption: "Same probe at d=1024 — preview; full sweep deferred to follow-up.", alt: "Causal effect at d=1024 (preview)" },

  // ---- Width sweep ----
  { id: "p-width-5panel",           src: F + "p-width-5panel.png",          caption: "Width sweep: per-(layer, head) prefix-match score at d ∈ {128, 256, 384, 512, 1024}. Compression vs. split visible.", alt: "5-panel width heatmaps" },
  { id: "p-width-crossover",        src: F + "p-width-crossover.png",       caption: "Best-head prefix-match score per layer vs. model width. Crossover near d=384.", alt: "Width crossover" },
  { id: "p-loss-w128",              src: F + "p-loss-w128.png",             caption: "Loss curve for sweep-w128-s0. Induction bump near step 30,000.", alt: "Loss curve d=128" },
  { id: "p-loss-w256",              src: F + "p-loss-w256.png",             caption: "Loss curve for sweep-w256-s0. Induction bump near step 60,000.", alt: "Loss curve d=256" },
  { id: "p-loss-w384",              src: F + "p-loss-w256.png",             caption: "Loss curve for sweep-w384-s0 (transition regime).", alt: "Loss curve d=384" },
  { id: "p-loss-w512",              src: F + "p-loss-w1024.png",            caption: "Loss curve for sweep-w512-s0.", alt: "Loss curve d=512" },
  { id: "p-loss-w1024",             src: F + "p-loss-w1024.png",            caption: "Loss curve for sweep-w1024-s0. Latest induction bump (~step 90,000).", alt: "Loss curve d=1024" },

  // ---- Induction score curves ----
  { id: "p-induction-vs-step",      src: F + "p-induction-vs-step.png",     caption: "Induction score per L1 head across training. L1H1 and L1H2 saturate near step 70,000; L1H0/H3 stay near chance.", alt: "Induction score across training" },
  { id: "p-induction-vs-step-w128", src: F + "p-induction-vs-step.png",     caption: "Same probe at d=128 — saturation earlier (step ~25,000).", alt: "Induction score d=128" },

  // ---- Data ----
  { id: "p-data-zipf",              src: F + "p-data-zipf.png",             caption: "Eval-data token-frequency Zipf log-log (OpenWebText slice 1 of 8).", alt: "Zipf log-log" },
  { id: "p-data-mix",               src: F + "p-gallery-data-mix.png",      caption: "OpenWebText slice domain mix (estimated).", alt: "Data mix" },
  { id: "p-data-batchsize-sanity",  src: F + "p-gallery-data-mix.png",      caption: "Eval batch size sanity: prefix-match score is stable across batch sizes 16–128.", alt: "Batch size sanity" },

  // ---- Diagnostics & dead-ends ----
  { id: "p-suspicious-spike-before",src: F + "p-suspicious-spike-before.png", caption: "Loss curve for sweep-w256-s0 before fix. The spike at step 12,000 was initially read as a phase transition — turned out to be a data-loader race condition.", alt: "Suspicious spike before fix" },
  { id: "p-suspicious-spike-after", src: F + "p-loss-w256.png",             caption: "Same training run after fix to prefetch_factor — no spike.", alt: "Loss curve after fix" },
  { id: "p-pathpatch-misconfig",    src: F + "p-gallery-pathpatch-misconfig.png", caption: "Path-patching with misconfigured corrupted prompt — all heads near zero. Bug caught in eval_data._make_corrupted.", alt: "Misconfigured path patching" },
  { id: "p-pathpatch-fixed",        src: F + "p-causal-effect-bars.png",    caption: "Same probe after the shuffle fix — recovers the expected per-head effect.", alt: "Path patching after fix" },
  { id: "p-ablation-matrix",        src: F + "p-gallery-ablation-matrix.png", caption: "Pairwise head-ablation matrix at d=256. Diagonal = single-head ablation (catastrophic for L1H1, L1H2).", alt: "Ablation matrix" },
  { id: "p-runtime-comparison",     src: F + "p-runtime-comparison.png",    caption: "Wall-clock comparison: activation patching vs attribution patching vs ACDC at d=256, batch 32.", alt: "Runtime comparison" },

  // ---- Paper figures ----
  { id: "p-headline-final",         src: F + "p-headline-final.png",        caption: "Final headline figure (publication quality, dpi=300). Best-head prefix-match per layer across widths.", alt: "Headline figure" },
  { id: "p-fig2-final",             src: F + "p-causal-effect-bars.png",    caption: "Figure 2: per-head causal effect at d=256 (paper-quality rendering).", alt: "Figure 2" },
  { id: "p-fig3-final",             src: F + "p-width-5panel.png",          caption: "Figure 3: width-sweep heatmaps (paper-quality rendering).", alt: "Figure 3" },
  { id: "p-fig4-supp",              src: F + "p-attn-pattern-l1h1.png",     caption: "Supplementary Figure 4: L1H1 attention pattern.", alt: "Supp Figure 4" },
  { id: "p-fig5-supp",              src: F + "p-induction-vs-step.png",     caption: "Supplementary Figure 5: induction score across training.", alt: "Supp Figure 5" },
  { id: "p-fig6-supp",              src: F + "p-replication-scatter.png",   caption: "Appendix A: replication scatter on held-out slice.", alt: "Replication scatter" },

  // ---- Verification ----
  { id: "p-replication-scatter",    src: F + "p-replication-scatter.png",   caption: "Replication scatter — per-head prefix-match score on original (slice 1) vs. replica (slice 2 of 8, seed 42).", alt: "Replication scatter" },
  { id: "p-replication-heatmap",    src: F + "p-head-pm-converged.png",     caption: "Held-out heatmap (replication run). L1H1=0.80, L1H2=0.78. Pattern is preserved.", alt: "Held-out heatmap" },

  // ---- Gallery only (removed from final draft, exploratory, sparkline backings) ----
  { id: "p-gallery-early-heatmap",  src: F + "p-gallery-early-heatmap.png", caption: "Discarded: head heatmap at step 25,000 — too early to be informative.", alt: "Early heatmap (discarded)" },
  { id: "p-gallery-data-mix",       src: F + "p-gallery-data-mix.png",      caption: "Exploratory: token-share by guessed domain category.", alt: "Data mix exploratory" },
  { id: "p-gallery-pathpatch-misconfig", src: F + "p-gallery-pathpatch-misconfig.png", caption: "Path-patching misconfig (kept as a reminder).", alt: "Misconfigured" },
  { id: "p-gallery-runtime",        src: F + "p-runtime-comparison.png",    caption: "Wall-clock seconds by patching method.", alt: "Runtime gallery" },
  { id: "p-gallery-ablation",       src: F + "p-gallery-ablation-matrix.png", caption: "Pairwise ablation matrix (exploratory).", alt: "Ablation gallery" },
  { id: "p-gallery-inset-1",        src: F + "p-loss-w128.png",             caption: "Loss curve inset used in Act I intro panel.", alt: "Inset 1" },
  { id: "p-gallery-inset-2",        src: F + "p-loss-w256.png",             caption: "Loss curve inset used in Act IV intro panel.", alt: "Inset 2" },
  { id: "p-gallery-inset-3",        src: F + "p-induction-vs-step.png",     caption: "Induction curve inset used in Act II intro panel.", alt: "Inset 3" },
  { id: "p-gallery-removed-1",      src: F + "p-gallery-early-heatmap.png", caption: "Removed-from-final-draft: very early checkpoint heatmap.", alt: "Removed 1" },
  { id: "p-gallery-removed-2",      src: F + "p-suspicious-spike-before.png", caption: "Removed-from-final-draft: the data-loader-race loss curve.", alt: "Removed 2" },
  { id: "p-gallery-removed-3",      src: F + "p-gallery-pathpatch-misconfig.png", caption: "Removed-from-final-draft: the misconfigured path-patch grid.", alt: "Removed 3" },
  { id: "p-gallery-supp-induction-w128",   src: F + "p-induction-vs-step.png",   caption: "Supplementary: induction-score-vs-step at d=128.", alt: "Supp d=128" },
  { id: "p-gallery-supp-loss-overlay",     src: F + "p-loss-w1024.png",          caption: "Supplementary: loss curves overlay across widths.", alt: "Supp overlay" },
];
